name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installa htmlhint
        run: npm install -g htmlhint

      - name: Controlla HTML
        run: htmlhint "*.html"

      - name: Controlla link rotti
        uses: lycheeverse/lychee-action@v1

  container-build:
    runs-on: ubuntu-latest
    needs: quality-check

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest